# nginx.conf
events {}
http {
    upstream backend {
        ip_hash;
        server alpha:80;
        server beta:80;
        server omega:80;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }
}